[package]
name = "kraken-api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.9"
anyhow = "1.0.94"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
log = "0.4.22"